[project]
name = "drone_hardware_demo"
version = "0.1.0"
description = "A demo integration showcasing how to create hardware integrations by simulating a drone"
readme = "README.md"
requires-python = ">=3.11"
dependencies = []
